version: 3
includes:
  01:01:
    taskfile: ./Taskfile.language.yaml
    dir: levels/01/01-FizzBuzz
  01:02:
    taskfile: Taskfile.language.yaml
    dir: levels/01/02-SquareJumpLoop
  01:03:
    taskfile: Taskfile.language.yaml
    dir: levels/01/03-OddSquaresOnly
  01:04:
    taskfile: Taskfile.language.yaml
    dir: levels/01/04-SmallSquareBigDouble
  01:05:
    taskfile: Taskfile.language.yaml
    dir: levels/01/05-ComplexLoop1
tasks:
  setup:
    desc: Setup the project
    cmds:
      - pls 01:01:setup
      - pls 01:02:setup
      - pls 01:03:setup
      - pls 01:04:setup
      - pls 01:05:setup
  gen:
    desc: Generate a new project
    cmds:
      - ./gen.sh {{.CLI_ARGS}}
