version: 3
includes:
  01:01:
    taskfile: ./Taskfile.language.yaml
    dir: levels/01/01-FizzBuzz
  01:02:
    taskfile: Taskfile.language.yaml
    dir: levels/01/02-SquareJumpLoop
  01:03:
    taskfile: Taskfile.language.yaml
    dir: levels/01/03-OddSquaresOnly
  01:04:
    taskfile: Taskfile.language.yaml
    dir: levels/01/04-SmallSquareBigDouble
  01:05:
    taskfile: Taskfile.language.yaml
    dir: levels/01/05-ComplexLoop1
  01:06:
    taskfile: Taskfile.language.yaml
    dir: levels/01/06-FactorialLoop
  01:07:
    taskfile: Taskfile.language.yaml
    dir: levels/01/07-ComplexLoopSum
tasks:
  setup:
    desc: Setup the project
    deps:
      - 01:01:setup
      - 01:02:setup
      - 01:03:setup
      - 01:04:setup
      - 01:05:setup
      - 01:06:setup
      - 01:07:setup
  gen:
    desc: Generate a new project
    cmds:
      - ./gen.sh {{.CLI_ARGS}}
